export enum State {
  WELCOME = 'WELCOME',
  MAIN_MENU = 'MAIN_MENU',
  PRICES_OVERVIEW = 'PRICES_OVERVIEW',
  BRANCH_SELECTION = 'BRANCH_SELECTION',
  BRANCH_MENU = 'BRANCH_MENU',
  BRANCH_PRICES = 'BRANCH_PRICES',
  BRANCH_PRICES_MONTHLY = 'BRANCH_PRICES_MONTHLY',
  BRANCH_PRICES_LONGTERM = 'BRANCH_PRICES_LONGTERM',
  CONTACT_MANAGER = 'CONTACT_MANAGER',

  // Booking flow
  BOOKING_BRANCH = 'BOOKING_BRANCH',
  BOOKING_TYPE = 'BOOKING_TYPE',
  BOOKING_DATE = 'BOOKING_DATE',
  BOOKING_TIME = 'BOOKING_TIME',
  BOOKING_CONFIRM = 'BOOKING_CONFIRM',

  // Content screens
  GROUP_CLASSES = 'GROUP_CLASSES',
  CLASS_DETAIL = 'CLASS_DETAIL',
  TRAINERS = 'TRAINERS',
  TRAINER_PROFILE = 'TRAINER_PROFILE',
  PROMOTIONS = 'PROMOTIONS',
  PROMO_DETAIL = 'PROMO_DETAIL',
}
